version: "2" 
plugins:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
exclude_patterns:
- spec/**/*
- tools/**/*
- index.js
- global.js
- getter.js
- "**/*.d.ts"
