language: node_js

node_js:
  - 6 # to be removed 2019-04-01
  - lts/*
  - node

before_install:
  - if [[ `npm -v` = 2* ]]; then npm i -g npm@3.10.8; fi

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
